pr: none
trigger:
  - release/v*
pool:
  vmImage: ubuntu-latest
extends:
  template: templates/azure-pipeline-step-deploy-appcode-release.yml
  parameters:
    environments: ${{ parameters.environments }}
parameters:
  - name: environments
    type: object
    default:
      - environmentName: test
        approvalNamePrefix: AppCode_
        pool_name: EE-WINDOWS-NONPROD
        variableGroupName: Common-AppBuild-Publish-Feed
        azDeployVariableGroupName: spn-netzero-appdev-deploy-nonprod
